#!/bin/bash

RED='\e[31m'
NOCOLOR='\033[0m'
GREEN='\e[92m'

arg=$1
raportsdirectory="zraports"

if [[ $arg == 'clean' ]]
  then
    rm -rf ${raportsdirectory};
    rm -rf phpcs-report.xml;
  elif [[ $arg == 'php' ]]
    then
      bin/console --ansi app:prepare-test-db -n --env=test;
      bin/phpunit;
  else
    mkdir ${raportsdirectory};
    yarn format;
    bin/console app:format-translations;
    vendor/bin/phpcs -n -p --report=junit --report-junit=phpcs-report.xml --report-full=${raportsdirectory}/phpcs-full-report.txt
    php bin/console --env=test cache:warmup;
    vendor/bin/phpstan analyse --error-format=junit --no-interaction --no-progress --memory-limit=-1 1> ${raportsdirectory}/phpstan-report.xml
    vendor/bin/php-cs-fixer fix -v --dry-run --diff --format=junit > ${raportsdirectory}/phpcsfixer-report.xml
fi
