#!/bin/bash

RED='\e[31m'
NOCOLOR='\033[0m'
GREEN='\e[92m'

CURRENTDATE=`date +"%Y%m%d"`

if [ -z "$1" ]
  then
    echo -e "${GREEN}Starting environment for master"
    git checkout master;
    git pull;
    php -d memory_limit=-1 /c/composer/composer.phar install;
    php -d memory_limit=-1 bin/console d:m:m --no-interaction ;
  else
    echo -e "${GREEN}Starting environment for task ${CURRENTDATE}_$1"
     git checkout master;
     git pull;
     git checkout -b "${CURRENTDATE}_$1";
     php -d memory_limit=-1 /c/composer/composer.phar install;
     php -d memory_limit=-1 bin/console d:m:m --no-interaction ;
fi


